admins:
  - philote-dev
  - BritishAmericqn
team_leads:
  - philote-dev
  - ericrcwu001
  - alsy7009
  - meric233
  - syz2026
  - gorpyshortlegs
  - hiyasvyas
  - pianomaster99
pilot_repositories:
  - OLMo-core
  - dolma
members:
  - {github_login: BritishAmericqn, display_name: Benjamin}
  - {github_login: ericrcwu001, display_name: Eric Wu}
  - {github_login: GMatherne}
  - {github_login: nzhao721}
  - {github_login: pianomaster99, display_name: Tom Liu}
  - {github_login: cd1313}
  - {github_login: IsabellaChen70}
  - {github_login: gorpyshortlegs, display_name: Arhant Choudhary}
  - {github_login: Elitelord}
  - {github_login: anshulmago1}
  - {github_login: arteexu}
  - {github_login: sidvenkatayogi}
  - {github_login: banksaj27}
  - {github_login: claire-mao}
  - {github_login: VS-code-cloud}
  - {github_login: Avaneesh-Ramesh-07}
  - {github_login: aryanjverma}
  - {github_login: William-2357}
  - {github_login: TejasviTyagi14}
  - {github_login: caiiris}
  - {github_login: yuen-kai}
  - {github_login: alsy7009, display_name: Amy Lin}
  - {github_login: Adarsh-Rajesh-Github}
  - {github_login: syz2026, display_name: Stephen Zhang}
  - {github_login: philote-dev, display_name: Frank Gonzalez}
  - {github_login: ninLi0}
  - {github_login: meric233, display_name: Meric Xing}
  - {github_login: hiyasvyas, display_name: Hiya Vyas}
  - {github_login: mathishard17}
  - {github_login: LawrenceDong71}
  - {github_login: katiehehe}
  - {github_login: alphaxia2100}
  - {github_login: NotAnAlgorithm}
